"""Generate docs/codebook.md from the configs, so docs cannot drift from code."""
import pathlib, sys, yaml
ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from lmstudy.code_regressors import load_dictionary

scope = yaml.safe_load((ROOT / "config" / "scope.yaml").read_text())
D = load_dictionary(ROOT / "config" / "regressors.yaml")

DERIVED = [
 ("posting_key","string","SHA1 of employer + normalized title + location; the dedup key."),
 ("employer","string","Employer name from the sampling frame."),
 ("industry","categorical","utility | data_center | cooperative | retailer | grid_operator | energy_analytics | developer | consulting | grid_vendor. Utility is the model's reference category."),
 ("role_family","categorical","siting_dev | regulatory | market_commercial | grid_power | ai_ml | gis | software_data | sustainability | other. Keeps a widened role taxonomy from silently pooling different pay regimes; software_data is the reference category."),
 ("job_level","ordinal","0 unlevelled, 1 = I/Associate/Junior, 2 = II/Analyst, 3 = III/Senior Associate. Records the rung on the early-career ladder. It does NOT decide early-career status; the experience parse does."),
 ("title","string","Posting title as published."),
 ("ats_platform","categorical","Which ATS served the posting. Provenance control, not a labor-market attribute."),
 ("metro","categorical","chicago | indianapolis (tier 3 metros if escalation triggers)."),
 ("tier","int","Scope tier the observation entered through."),
 ("state","string","State of the resolved work location."),
 ("mandate_state","binary","1 if the state mandates pay disclosure in postings (IL yes, IN no)."),
 ("distance_miles","numeric","Great-circle miles from the metro centroid; blank for location-free remote postings."),
 ("work_arrangement","categorical","onsite | hybrid | remote | unspecified."),
 ("remote_eligible","binary","1 if the posting is remote-eligible."),
 ("posted_at","date","Publication timestamp as reported by the ATS."),
 ("posting_age_days","numeric","Days between posted_at and the build date."),
 ("first_seen_run","date","First collection run that observed this posting."),
 ("last_seen_run","date","Most recent run that observed it; with first_seen it gives time-on-market."),
 ("yrs_exp_min","numeric","Minimum years of experience parsed from the text; blank if unstated."),
 ("pay_disclosed","binary","1 if a usable pay figure was found. The selection indicator."),
 ("pay_min / pay_max","numeric","Annualized USD range bounds."),
 ("pay_midpoint","numeric","Annualized midpoint. log of this is the dependent variable."),
 ("pay_range_width","numeric","pay_max - pay_min. Secondary outcome: employer pay-setting uncertainty."),
 ("pay_source","categorical","structured (ATS field) | text (parsed from description)."),
 ("pay_unit_original","categorical","year | hour | month, before annualizing."),
 ("hourly_original","binary","1 if the posting quoted an hourly rate (annualized at 2,080 hrs)."),
 ("pay_single_figure","binary","1 if a point value rather than a range was found. Exclude in robustness checks."),
 ("description_hash","string","SHA256 prefix of the description, for integrity checking."),
 ("description_chars","numeric","Description length; a rough control for posting detail."),
]

def esc(text: str) -> str:
    """Escape pipes so values like 'utility | data_center' do not break the table."""
    return str(text).replace("|", "\\|")


lines = ["# Codebook", "",
 f"Dependent variable: **{scope['study']['dependent_variable']}**.", "",
 "Generated by `scripts/make_codebook.py` from `config/scope.yaml` and",
 "`config/regressors.yaml`. Do not edit by hand.", "",
 "## Identifiers, context, and outcome variables", "",
 "| Variable | Type | Definition |", "|---|---|---|"]
for name, typ, desc in DERIVED:
    lines.append(f"| `{esc(name)}` | {typ} | {esc(desc)} |")

lines += ["", "## Coded regressors", "",
 f"{len(D)} regressors coded from posting text by word-boundary pattern matching.",
 "A negation pattern forces an otherwise-positive match back to 0.", ""]
by_group = {}
for name, spec in D.items():
    by_group.setdefault(spec["group"], []).append((name, spec))
for group, items in by_group.items():
    lines += [f"### {group.replace('_',' ').title()}", "",
              "| Variable | Definition | Example patterns | Negations |", "|---|---|---|---|"]
    for name, spec in items:
        pats = ", ".join(f"`{p}`" for p in spec.get("patterns", [])[:4])
        if len(spec.get("patterns", [])) > 4:
            pats += f", … ({len(spec['patterns'])} total)"
        negs = ", ".join(f"`{n}`" for n in spec.get("negations", [])) or "—"
        lines.append(f"| `{name}` | {esc(spec.get('description',''))} | {pats} | {negs} |")
    lines.append("")

out = ROOT / "docs" / "codebook.md"
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out} ({len(D)} regressors, {len(DERIVED)} derived variables)")
